name: Metin2 News Bot

on:
  schedule:
    - cron:  '0 * * * *'   # jede volle Stunde
  workflow_dispatch:

jobs:
  hourly-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hourly check
        run: |
          . venv/bin/activate
          python run_once.py
